---
- hosts: guests:extras
  become: yes
  gather_facts: no
  tasks:
    - apt: name=mysql-server
    - apt: name=memcached
    - shell: mysql -u root -NBe 'ALTER USER "root"@"localhost" IDENTIFIED WITH mysql_native_password BY "";'
