- hosts: guests:extras
#- hosts: extras
  become: yes
  become_user: isucon
  gather_facts: no
  tasks:
    - name: create mysqldump
      get_url: url=https://s3-ap-northeast-1.amazonaws.com/neko-neko-files/dump.sql.bz2 dest=/home/isucon/backup/mysqldump.sql.bz2 force=1
    - name: create database
      shell: bzcat /home/isucon/backup/mysqldump.sql.bz2 | mysql -u root
